// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.27.3
// source: proto/service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_proto_service_proto protoreflect.FileDescriptor

const file_proto_service_proto_rawDesc = "" +
	"\n" +
	"\x13proto/service.proto\x12\vgrpcservice\x1a\x11proto/model.proto2\xa3\x04\n" +
	"\vUserService\x12=\n" +
	"\x04Noop\x12\x19.grpcservice.EmptyRequest\x1a\x1a.grpcservice.EmptyResponse\x12D\n" +
	"\aGetUser\x12\x1b.grpcservice.GetUserRequest\x1a\x1c.grpcservice.GetUserResponse\x12M\n" +
	"\n" +
	"CreateUser\x12\x1e.grpcservice.CreateUserRequest\x1a\x1f.grpcservice.CreateUserResponse\x12M\n" +
	"\n" +
	"UpdateUser\x12\x1e.grpcservice.UpdateUserRequest\x1a\x1f.grpcservice.UpdateUserResponse\x12M\n" +
	"\n" +
	"DeleteUser\x12\x1e.grpcservice.DeleteUserRequest\x1a\x1f.grpcservice.DeleteUserResponse\x12J\n" +
	"\tListUsers\x12\x1d.grpcservice.ListUsersRequest\x1a\x1e.grpcservice.ListUsersResponse\x12V\n" +
	"\rListUserTypes\x12!.grpcservice.ListUserTypesRequest\x1a\".grpcservice.ListUserTypesResponse2d\n" +
	"\vTestService\x12U\n" +
	"\x10TestNumericTypes\x12\x1f.grpcservice.NumericTestRequest\x1a .grpcservice.NumericTestResponseB(Z&github.com/instaunit/grpcservice/protob\x06proto3"

var file_proto_service_proto_goTypes = []any{
	(*EmptyRequest)(nil),          // 0: grpcservice.EmptyRequest
	(*GetUserRequest)(nil),        // 1: grpcservice.GetUserRequest
	(*CreateUserRequest)(nil),     // 2: grpcservice.CreateUserRequest
	(*UpdateUserRequest)(nil),     // 3: grpcservice.UpdateUserRequest
	(*DeleteUserRequest)(nil),     // 4: grpcservice.DeleteUserRequest
	(*ListUsersRequest)(nil),      // 5: grpcservice.ListUsersRequest
	(*ListUserTypesRequest)(nil),  // 6: grpcservice.ListUserTypesRequest
	(*NumericTestRequest)(nil),    // 7: grpcservice.NumericTestRequest
	(*EmptyResponse)(nil),         // 8: grpcservice.EmptyResponse
	(*GetUserResponse)(nil),       // 9: grpcservice.GetUserResponse
	(*CreateUserResponse)(nil),    // 10: grpcservice.CreateUserResponse
	(*UpdateUserResponse)(nil),    // 11: grpcservice.UpdateUserResponse
	(*DeleteUserResponse)(nil),    // 12: grpcservice.DeleteUserResponse
	(*ListUsersResponse)(nil),     // 13: grpcservice.ListUsersResponse
	(*ListUserTypesResponse)(nil), // 14: grpcservice.ListUserTypesResponse
	(*NumericTestResponse)(nil),   // 15: grpcservice.NumericTestResponse
}
var file_proto_service_proto_depIdxs = []int32{
	0,  // 0: grpcservice.UserService.Noop:input_type -> grpcservice.EmptyRequest
	1,  // 1: grpcservice.UserService.GetUser:input_type -> grpcservice.GetUserRequest
	2,  // 2: grpcservice.UserService.CreateUser:input_type -> grpcservice.CreateUserRequest
	3,  // 3: grpcservice.UserService.UpdateUser:input_type -> grpcservice.UpdateUserRequest
	4,  // 4: grpcservice.UserService.DeleteUser:input_type -> grpcservice.DeleteUserRequest
	5,  // 5: grpcservice.UserService.ListUsers:input_type -> grpcservice.ListUsersRequest
	6,  // 6: grpcservice.UserService.ListUserTypes:input_type -> grpcservice.ListUserTypesRequest
	7,  // 7: grpcservice.TestService.TestNumericTypes:input_type -> grpcservice.NumericTestRequest
	8,  // 8: grpcservice.UserService.Noop:output_type -> grpcservice.EmptyResponse
	9,  // 9: grpcservice.UserService.GetUser:output_type -> grpcservice.GetUserResponse
	10, // 10: grpcservice.UserService.CreateUser:output_type -> grpcservice.CreateUserResponse
	11, // 11: grpcservice.UserService.UpdateUser:output_type -> grpcservice.UpdateUserResponse
	12, // 12: grpcservice.UserService.DeleteUser:output_type -> grpcservice.DeleteUserResponse
	13, // 13: grpcservice.UserService.ListUsers:output_type -> grpcservice.ListUsersResponse
	14, // 14: grpcservice.UserService.ListUserTypes:output_type -> grpcservice.ListUserTypesResponse
	15, // 15: grpcservice.TestService.TestNumericTypes:output_type -> grpcservice.NumericTestResponse
	8,  // [8:16] is the sub-list for method output_type
	0,  // [0:8] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_proto_service_proto_init() }
func file_proto_service_proto_init() {
	if File_proto_service_proto != nil {
		return
	}
	file_proto_model_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_service_proto_rawDesc), len(file_proto_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_service_proto_goTypes,
		DependencyIndexes: file_proto_service_proto_depIdxs,
	}.Build()
	File_proto_service_proto = out.File
	file_proto_service_proto_goTypes = nil
	file_proto_service_proto_depIdxs = nil
}
